---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: vladpugachev/backend:0.1
        ports:
          - containerPort: 9000
        imagePullPolicy: IfNotPresent
        name: backend
        volumeMounts:
          - mountPath: "/backend/static"
            name: my-volume
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: pvc