apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontwhithback
  name: frontwhithback
  namespace: stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontwhithback
  template:
    metadata:
      labels:
        app: frontwhithback
    spec:
      containers:
      - image: vladpugachev/backend:0.1
        imagePullPolicy: IfNotPresent
        name: backend
        volumeMounts:
          - mountPath: "/backend/static"
            name: my-volume
      - image: vladpugachev/frontend:0.1
        imagePullPolicy: IfNotPresent
        name: frontend
        volumeMounts:
          - mountPath: "/frontend/static"
            name: my-volume
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: my-volume
          emptyDir: {}
